server:
  port: 8081

#cors:
#  originPatterns: http://localhost:3000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
logging:
  level:
    org:
      _org.springframework.web.servlet.HandlerMapping.Mappings: debug
      springframework:
        web:
          nodeValue: INFO
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        nodeValue: INFO
        SQL: DEBUG
   # name: C:/Desenvolvimento/log/app-cliente.log
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DB_LOGIN
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      database: DB_LOGIN
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#        format_sql: true
#        generate-ddl: true
#        open-in-view: false
  flyway:
    baselineOnMigrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    
springdoc:
  api-docs:
    path: /api-docs
